server:
  tomcat.uri-encoding: UTF-8
  port: 8182

spring:
  resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/Users/lzz/work/java/jjqnr/web/dist